### ISSUE TITLE
Automatické posunutí obsahu celé stránky pod AdminBar

### ISSUE THREAD

**Issue by janbarasek** [baraja-core/admin-bar#8]
Tento balík přidává černý admin bar do všech stránek, pokud je uživatel přihlášen.

Bar se automaticky přes CSS styl pozicuje fixně na začátku stránky. Styly jsou pak umístěny přímo v tomto balíku, přičemž balík zajišťuje jejich korektní vykreslení do stránky, pokud je Bar zobrazen.

Styly: https://github.com/baraja-core/admin-bar/blob/master/src/assets/style.css

Šablona je pak implementována jako `phtml` soubor, který je optimalizován na rychlost renderu: https://github.com/baraja-core/admin-bar/blob/master/src/assets/content.phtml

----

Při vykreslení Baru se stává, že se vykreslí přes hlavní obsah stránky.

Příklad:

![Snímek obrazovky 2021-08-13 v 9 55 19](https://user-images.githubusercontent.com/4738758/129323828-e7feb61b-14e6-4c50-8c4d-2bac928f715c.png)

Zkus vymyslet způsob, jak obsah stránky posunout o fixní počet pixelů (Bar je vždy stejně vysoký, rozměry najdeš ve stylu) a tím se zajistí, že bude stránka korektně vidět.

Například takto:

![Snímek obrazovky 2021-08-13 v 9 56 13](https://user-images.githubusercontent.com/4738758/129323943-54e48337-4bbb-4a1c-bf4e-0b58699e04cb.png)

Řešení si představuji tak, že se posune obsah `<body>` o fixní horní margin, zatímco Bar bude pozicován fixně, takže zůstane na začátku stránky.

Logiku testuj v libovolném projektu a pak sem pošli Pull request.

Díky.

**Comment by danieldobry370** [comment]
Stačí jen přidat do `baraja-core\admin-bar-src-\assets\style.css`:

```css
body {
	margin-top: 45px;
}
```

**Comment by janbarasek** [comment]
Funguje to, i když má stránka fixní hlavičku?

**Comment by janbarasek** [comment]
Řešení musí fungovat i v případě, kdy si web fixuje hlavičku přes CSS styl `top: 0` (navíc tam může mít přepínač `important`). Nezapomeň na obecnost. Stránka nemusí obsahovat `<body>` element a pozice prvků může být vypočítána dynamicky.

Teoretické řešení:

> Hrubá představa je ta, že admin bar vykreslíš na zápornou souřadnici, tj. top bude na -25px, a potom se ti povede posunout celou stránku dolů, protože jakékoli jiné řešení nemusí fungovat obecně, a taky nesmíš nikdy rozbít javascript, pokud náhodou na stránce nějak počítá rozměry.

**Comment by janbarasek** [comment]
Problém zafixování hlavičky řešil třeba i sám Google v jeho náhledu historie stránky. Zkus prozkoumat jeho implementaci:

![Snímek obrazovky 2021-08-16 v 15 01 17](https://user-images.githubusercontent.com/4738758/129567816-2fd7cbf5-5615-4696-a585-fbc1db918494.png)

Stačí do Googlu zadat: `cache:php.baraja.cz`.

**Comment by danieldobry370** [comment]
Řešení googlu taky není bez chyby. Celou stránku zabalí do divu a nepočítá s prvkem který má position-top:0.
![image](https://user-images.githubusercontent.com/88149154/129568578-dd159aa6-b250-4fcb-98a4-494b08e3395b.png)

**Comment by janbarasek** [comment]
Chápu. Zkus najít nějaké vhodné řešení, které bude mít co nejméně nevýhod a bude fungovat na co největší množství případů.

Pravděpodobně budeme muset součástí CMS napsat pravidlo, jak se má správně šablona konfigurovat, aby s Admin Barem vypadala vždy dobře.

**Comment by danieldobry370** [comment]
Přesně tak. Co se týče wordpressu tak ani ten nějak nebojuje s position-top: 0. Tvůrci šablon prostě ten styl nepoužívají.

**Comment by danieldobry370** [comment]
Adminbar wordpressu po přenastavení navigace na position: 0 v css souboru. 
![image](https://user-images.githubusercontent.com/88149154/129569249-55d23c7a-71f2-4e95-b9fe-8ce582baf500.png)

**Comment by janbarasek** [comment]
Pojďme to zatím udělat jen přes ten CSS selector pro `body` a časem promyslíme lepší řešení.
